/**
 * Ambient description parsing — pure functions with no PixiJS dependency.
 *
 * Extracts ambient effect types from natural-language sceneConfig.ambientDescription
 * strings generated by the Loci (metaphor agent).
 */

// ─── Ambient Effect Types ─────────────────────────────────────

export type AmbientEffectType = 'vignette' | 'particles-drift' | 'particles-float' | 'particles-fall' | 'scene-pulse'

interface AmbientRule {
  pattern: RegExp
  effect: AmbientEffectType
}

const AMBIENT_RULES: AmbientRule[] = [
  { pattern: /\b(safelight|glow|amber|luminous|warm light|lantern|candle)/i, effect: 'vignette' },
  { pattern: /\b(steam|mist|fog|haze|vapor|smoke|fume)/i,                    effect: 'particles-drift' },
  { pattern: /\b(dust|mote|speck|particle|firefl)/i,                          effect: 'particles-float' },
  { pattern: /\b(rain|drip|water|drop|trickle|pour)/i,                        effect: 'particles-fall' },
  { pattern: /\b(puls|throb|flicker|heartbeat|breath)/i,                      effect: 'scene-pulse' },
]

/** Parse ambientDescription into a set of effect types */
export function parseAmbientDescription(desc: string): Set<AmbientEffectType> {
  const effects = new Set<AmbientEffectType>()
  for (const rule of AMBIENT_RULES) {
    if (rule.pattern.test(desc)) {
      effects.add(rule.effect)
    }
  }
  return effects
}
